import React, { useCallback, useEffect, useState } from 'react';
import { FileDown, FileSpreadsheet, Database, AlertCircle, RefreshCw } from 'lucide-react';
import { fetchStats, getDownloadUrl, describeError, isAbortError } from '../services/api';
import type { SpeciesBreakdown } from '../types';

/** Backend may send Unix seconds or milliseconds — treat >= 1e12 as ms. */
const formatUpdatedAt = (updatedAt?: number): string => {
  if (updatedAt === undefined || updatedAt === null) return '—';
  const ms = updatedAt >= 1e12 ? updatedAt : updatedAt * 1000;
  const d = new Date(ms);
  if (Number.isNaN(d.getTime())) return '—';
  return d.toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });
};

const Download: React.FC = () => {
  const [datasets, setDatasets] = useState<SpeciesBreakdown[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async (signal?: AbortSignal) => {
    setLoading(true);
    setError(null);
    try {
      const stats = await fetchStats(signal);
      setDatasets(stats.breakdown ?? []);
    } catch (err) {
      if (isAbortError(err)) return;
      setError(describeError(err));
    } finally {
      if (!signal?.aborted) setLoading(false);
    }
  }, []);

  useEffect(() => {
    const ctrl = new AbortController();
    load(ctrl.signal);
    return () => ctrl.abort();
  }, [load]);

  const handleRetry = () => {
    load();
  };

  const handleDownload = (species: string) => {
    // Anchor-click instead of window.location.href so a backend error page
    // never replaces the SPA and loses client state.
    const a = document.createElement('a');
    a.href = getDownloadUrl(species);
    a.download = '';
    a.rel = 'noopener';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  if (loading) {
    return (
      <div className="flex flex-1 items-center justify-center py-24" role="status" aria-label="Loading datasets">
        <div className="h-8 w-8 animate-spin rounded-full border-2 border-journal-300 border-t-navy-700" />
        <span className="sr-only">Loading available datasets…</span>
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-fade-in">
      <div>
        <h1 className="font-serif text-navy-900">Download Data</h1>
        <p className="text-journal-700 max-w-3xl">
          Access full datasets generated by our pipeline. These files represent a real-time snapshot of the
          current database. All data is available under the{' '}
          <strong>Creative Commons Attribution 4.0 International License (CC BY 4.0)</strong>.
        </p>
      </div>

      {error ? (
        <div
          role="alert"
          className="flex flex-col items-start gap-3 rounded-md border border-burgundy-200 bg-burgundy-50 p-6"
        >
          <div className="flex items-center gap-2 text-burgundy-800">
            <AlertCircle className="h-5 w-5 shrink-0" />
            <p className="font-medium">Failed to load the dataset list.</p>
          </div>
          <p className="text-sm text-burgundy-700">{error}</p>
          <button
            onClick={handleRetry}
            className="inline-flex items-center gap-2 rounded-md bg-navy-800 px-4 py-2 text-sm font-medium text-white hover:bg-navy-700"
          >
            <RefreshCw className="h-4 w-4" />
            Retry
          </button>
        </div>
      ) : datasets.length === 0 ? (
        <div className="rounded-md border border-journal-200 bg-white p-12 text-center">
          <Database className="mx-auto mb-4 h-16 w-16 text-journal-300" />
          <p className="font-serif text-lg text-journal-600">No datasets available in the database yet.</p>
        </div>
      ) : (
        <div className="divide-y divide-journal-100 rounded-md border border-journal-200 bg-white">
          {datasets.map((d) => (
            <div
              key={d.species}
              className="flex flex-col gap-4 p-6 transition-colors hover:bg-journal-50 sm:flex-row sm:items-center sm:justify-between"
            >
              <div className="flex items-start gap-4">
                <div className="rounded-md bg-navy-50 p-3 text-navy-700">
                  <FileSpreadsheet className="h-6 w-6" />
                </div>
                <div>
                  <h2 className="font-serif text-lg text-navy-900">{d.species} Dataset</h2>
                  <p className="mt-1 text-sm text-journal-600">
                    Complete peak annotations and metadata for <em>{d.species}</em>.
                  </p>
                  <div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-journal-500">
                    <span className="tnum">{d.count.toLocaleString()} Records</span>
                    <span aria-hidden="true">&bull;</span>
                    <span>Updated: {formatUpdatedAt(d.updatedAt)}</span>
                    <span aria-hidden="true">&bull;</span>
                    <span>Format: TSV</span>
                  </div>
                </div>
              </div>
              <button
                onClick={() => handleDownload(d.species)}
                className="inline-flex shrink-0 items-center justify-center gap-2 self-start rounded-md bg-navy-800 px-4 py-2 text-sm font-medium text-white hover:bg-navy-700 sm:self-center"
              >
                <FileDown className="h-4 w-4" />
                Download
              </button>
            </div>
          ))}
        </div>
      )}

      <div className="rounded-md border border-journal-200 bg-journal-50 p-6">
        <h3 className="font-serif text-journal-800">Terms of Use</h3>
        <p className="text-sm text-journal-600">
          When using this data in your publications, please cite CREDB — see the <strong>How to Cite</strong>{' '}
          section in the footer of this page. Files are generated on-demand from the database and reflect its
          current contents.
        </p>
      </div>
    </div>
  );
};

export default Download;
